python: can't open file 'file': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'user' is not defined
